#
# This is a Flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1), manifest.toml(5) for more information.
#
# Flox manifest version managed by Flox CLI
version = 1

[install]
nodejs.pkg-path = "nodejs"
jq.pkg-path = "jq"
python3.pkg-path = "python3"
gnumake.pkg-path = "gnumake"
bash.pkg-path = "bash"

[vars]
[hook]
on-activate = '''
npm i --silent 
echo '     ╔═════════════════════════════════════════════════════╗'
echo '     ║                                                     ║'
echo '     ║  There are two services in this environment.        ║'
echo '     ║  You can start them using "flox services start"     ║'
echo '     ║                                                     ║'
echo '     ║  This will start services for the web front end     ║'
echo '     ║    and a proxy.                                     ║'
echo '     ║                                                     ║'
echo '     ║  Visit port http://localhost:8000 for               ║' 
echo '     ║    developement work.                               ║'
echo '     ║                                                     ║'
echo '     ╚═════════════════════════════════════════════════════╝'
'''

[profile]

# The `[services]` section of the manifest allows you to define services.
# Services defined here use the packages provided by the `[install]` section
# and any variables you've defined in the `[vars]` section or `hook.on-activate` script.
[services]
# postgres.command = "postgres --config-file=pg.conf"
proxy.command = "node proxy.mjs"
frontend.command = "python -m http.server"

# Additional options can be set in the `[options]` section. Refer to
# manifest.toml(5) for a list of available options.
[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
# Uncomment to disable CUDA detection.
cuda-detection = false
